version: "3"
services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: v3
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gorima
      MYSQL_PASSWORD: gorima
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./server
    restart: always
    container_name: backend
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks:
      - app-network


volumes:
  db_data:


networks:
  app-network:
    driver: bridge
